### ISSUE TITLE
Building v8ppc

### ISSUE THREAD

**Issue by jscottandersonthe1** [andrewlow/v8ppc#125]
I've read that the ppc porting work has been folded in to the main v8 repository.  True?
Is this repository, andrewlow/v8ppc, still the best place to access the v8 ppc porting activity?
Lastly, I am unable to build on this tree.  I've done the straight up clone and tried to build:
    git clone  https://github.com/andrewlow/v8ppc.git
    make ppc nativesim=true
I get:
    make: *** No rule to make target `third_party/icu/icu.gypi', needed by `out/Makefile.ppc.release'.  Stop.
I have installed depot tools and added the tools to my path.
I can build the regular v8 tree, but I don't see the nativesim symbol in there.
Finally, my workstation is an Intel Linux box.  Am I missing something about building a simulated ppc library, or is just a make ppc sufficient to do that?

Thanks for any light you can shed on this.  I'm working on a port to the Freescale e300c3 core and I'm just trying to develop the tool proficiency to converse here.

**Comment by mhdawson** [comment]
The ppc port has been contributed back to the main v8 repository.  At this point the v8ppc repo is mainly used to stage the changes required to keep ppc to to date in the main v8 repository.

Its also the best place to contribute independent changes.  I'd suggest though that you might want to start with the beta branch (currently 4.8 I believe) since there is some delay between when platform specific changes go in and when we add the corresponding changes for PPC. 

We are the owners of the ppc directories in the main v8 repository keeping us in the loop/discussing changes here is still a good idea in order to get feedback in advance of submitting changes to the main repo.

Can you expand on what you mean when you say "I can build the regular v8 tree, but I don't see the nativesim symbol in there."

In terms of building on Intel linux, that does work and its built for ppc both in our internal builds and in the google build system (ppc section in https://build.chromium.org/p/client.v8.branches/console and   https://build.chromium.org/p/client.v8/console)

From what I can see our current build uses this command 

make -j8 ppc i18nsupport=off V=1

i18nsupport=off is used because some of the test artifacts are not set up to support big endian.

**Comment by jscottandersonthe1** [comment]
@mhdawson First off thanks!
When looking at the examples I see the suggestion to use nativesim=true as an argument to make.  In the v8ppc tree I found that symbol in the Makefile, but I didn't find it in the main v8 Makefile.  That is I've cloned both repositories and can't find that build option in v8.  But now I have to apologize and note that I can't find it either place.  In any event, I cannot build the v8ppc tree (is that the right term?) at all, while I can build the v8 (including with my cross toolchain).  I'm new to git and building with gyp though, so I'm going back and reading through again.  It just seemed that the v8ppc from memory that is set up to use something other than the depot tools and it gripes when I try to make dependencies.

**Comment by mtbrandy** [comment]
You shouldn't have to specify anything special to get the PPC simulator on your Intel host.  Perhaps the issue is the way you're setting up the clone and gclient config?  Try the following steps:

Clone v8ppc into v8 dir:

    git clone git@github.com:andrewlow/v8ppc.git v8

Retrieve dependencies (with depot_tools in your path):

    gclient config --spec "solutions = [{'name': 'v8', 'url': 'git@github.com:andrewlow/v8ppc.git'}]"
    gclient sync

Build all POWER targets:

    cd v8
    make -j8 ppc ppc64

**Comment by jscottandersonthe1** [comment]
@mtbrandy Thank you!  That worked nicely.

**Comment by jscottandersonthe1** [comment]
The instructions put me on the right path, but the url does not work for me.  Most people besides me probably already knew that they'd have to use "https://" instead of "git@"

**Comment by jscottandersonthe1** [comment]
Any thoughts on what I might have missed here?  I thought I'd duplicated my work machine, but this is not working at all the same.
    [janderson@localhost v8]$ make -j8 ppc ppc64
PYTHONPATH="/home/janderson/workspace/v8/tools/generate_shim_headers:/home/janderson/workspace/v8/build::/home/janderson/workspace/v8/build/gyp/pylib:" \
GYP_GENERATORS=make \
build/gyp/gyp --generator-output="out" build/all.gyp \
              -Ibuild/standalone.gypi --depth=. \
              -Dv8_target_arch=ppc \
               \
               \
              -S.ppc.release  -Dv8_enable_backtrace=1 -Darm_fpu=default -Darm_float_abi=default
PYTHONPATH="/home/janderson/workspace/v8/tools/generate_shim_headers:/home/janderson/workspace/v8/build::/home/janderson/workspace/v8/build/gyp/pylib:" \
GYP_GENERATORS=make \
build/gyp/gyp --generator-output="out" build/all.gyp \
              -Ibuild/standalone.gypi --depth=. \
              -Dv8_target_arch=ppc \
               \
               \
              -S.ppc.debug  -Dv8_enable_backtrace=1 -Darm_fpu=default -Darm_float_abi=default
PYTHONPATH="/home/janderson/workspace/v8/tools/generate_shim_headers:/home/janderson/workspace/v8/build::/home/janderson/workspace/v8/build/gyp/pylib:" \
GYP_GENERATORS=make \
build/gyp/gyp --generator-output="out" build/all.gyp \
              -Ibuild/standalone.gypi --depth=. \
              -Dv8_target_arch=ppc64 \
               \
               \
              -S.ppc64.release  -Dv8_enable_backtrace=1 -Darm_fpu=default -Darm_float_abi=default
PYTHONPATH="/home/janderson/workspace/v8/tools/generate_shim_headers:/home/janderson/workspace/v8/build::/home/janderson/workspace/v8/build/gyp/pylib:" \
GYP_GENERATORS=make \
build/gyp/gyp --generator-output="out" build/all.gyp \
              -Ibuild/standalone.gypi --depth=. \
              -Dv8_target_arch=ppc64 \
               \
               \
              -S.ppc64.debug  -Dv8_enable_backtrace=1 -Darm_fpu=default -Darm_float_abi=default
make[1]: Entering directory `/home/janderson/workspace/v8/out'
  CXX(target) /home/janderson/workspace/v8/out/ppc.debug/obj.target/v8_base/src/accessors.o
  CXX(target) /home/janderson/workspace/v8/out/ppc.debug/obj.target/v8_base/src/address-map.o
  CXX(target) /home/janderson/workspace/v8/out/ppc.debug/obj.target/v8_base/src/allocation.o
  CXX(target) /home/janderson/workspace/v8/out/ppc.debug/obj.target/v8_base/src/allocation-site-scopes.o
  CXX(target) /home/janderson/workspace/v8/out/ppc.debug/obj.target/v8_base/src/api-experimental.o
  CXX(target) /home/janderson/workspace/v8/out/ppc.debug/obj.target/v8_base/src/api.o
make[1]: Entering directory `/home/janderson/workspace/v8/out'
  CXX(target) /home/janderson/workspace/v8/out/ppc64.release/obj.target/v8_base/src/accessors.o
make[1]: Entering directory `/home/janderson/workspace/v8/out'
  CXX(target) /home/janderson/workspace/v8/out/ppc64.debug/obj.target/v8_base/src/accessors.o
In file included from ../src/accessors.cc:5:
In file included from .././src/accessors.h:8:
.././include/v8.h:7095:29: error: cast from pointer to smaller type 'intptr_t' (aka 'int') loses information
    return static_cast<int>(reinterpret_cast<intptr_t>(value)) >> shift_bits;

**Comment by jscottandersonthe1** [comment]
I believe this issue is resolved and can be closed.
